name: mohammed_elghanam_professional_hub
description: Native Flutter mobile executive portfolio for Mohammed Elghanam.
publish_to: "none"
version: 1.1.0+2

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.2
  pdfrx: ^2.4.7
  pdf: ^3.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
